services:
  - docker

language: python

python:
  - 3.6

cache: pip

install:
  - docker-compose -f docker-compose.yml -f docker-compose.travis.yml build

script:
  - docker-compose -f docker-compose.yml -f docker-compose.travis.yml run api "make quality"
  - docker-compose -f docker-compose.yml -f docker-compose.travis.yml run api "make detect_missing_migrations"
  - docker-compose -f docker-compose.yml -f docker-compose.travis.yml run api "make migrate"
  - docker-compose -f docker-compose.yml -f docker-compose.travis.yml run api "make test"

after_success:
  - pip install -U codecov
  - docker-compose run api coverage xml
  - codecov

env:
  matrix:
    secure: X7TwUDKbjesMbgWtit8XwTaWBkvL2+CMbIkNusBMTVnP+Rwg+xFFipotPfcvqRhC6UjqNcOEoZssuSL7bCFSV5DJprMuEgiQuEXdg/kbZtFeDQvRR+Xu96irr//73N45UfERYJguqYtKuYQtVasLf9EJVtwE1SPOrkABIbQFKid6w8kd520QB6+Nr6nZwL+/Pgbn/t1n7XsLQ52IA+G1dfb2c0a47N5hIyIzVIHy/7wya7BzoPn9j6SBIqIVj4Z1sshZCbrBqL/Za1sgviQboNuqS80gJImykLbBY7Ql02eAE9LRQ9yM20zqMBC5pM4Z+XD51GqMksLNaL8RMXbMiFL5b0SPIrWXgUedJqZa1aNM1g6D1FQ4ffCQ9AUhvXNh6/aPwE9aAVCIIFky+CgyIK/yHp2EwHJ3F7QhGsEwkuCK5Tm8bjEoLAnkVEgUWTR2eyTFWywd60bUINmFAXVD4oCYVELvDASLQsJ5aVFnWU8mHNgSlKToeg7pHR6AOK2KPpmZrk1KeVfYfodn0V7PRLsvgnBRZAd32djSY3nlK/D601ziKy/Fiv/bD8tuBrI4x3AufyNtngouYYpGw+idK8yxzJDxhNSsyYJRYyDf/A02t3JVpXz3XeHdF2Ji6qBtw7z5SkKfAx9hFUPxn+P2vE7DjlVs6IkFWhPY5ZaW1T4=
