services:
  - docker

language: python

python:
  - 3.6

cache: pip

install:
  - make docker.pull
  - make docker.build

script:
  - docker-compose -f docker-compose.yml -f docker-compose.travis.yml run app "make quality"
  - docker-compose -f docker-compose.yml -f docker-compose.travis.yml run app "make detect_missing_migrations"
  - docker-compose -f docker-compose.yml -f docker-compose.travis.yml run app "make migrate"
  - docker-compose -f docker-compose.yml -f docker-compose.travis.yml run app "make test"

after_success:
  - pip install -U codecov
  - docker exec -t woeip.app coverage xml
  - codecov
