services:
  - docker

language: python

python:
  - 3.6

cache: pip

install:
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml build

script:
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml run api /bin/bash "make quality"
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml run api /bin/bash "make detect_missing_migrations"
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml run api /bin/bash "make migrate"
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml run api /bin/bash "make test"

after_success:
  - pip install -U codecov
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml run api /bin/bash "coverage xml"
  - codecov

env:
  matrix:
    secure: tAFix+d0CPAU4k6u3XcAUpDys4VErQXjqSOWP+7UWwt1jbaB0iHbQCjoX93XY0yiFbIMurqIQ7Y6ok3ALnJZ0BA7bRrztnwPiJujZH8EauYWxDfaPVThgc+2iSfHmRBOUC04vy6u5PMpyQamAihBYGITeWDJp5K6ljkYwjh4sdobv+/bVxUW8s6x6DgRDJvlDRWDy7OGwDLWxJo+VfR+7VGBjCDiEaBAgUgX/bg2x4ZhMZw1np0X892rrTnjkd9OJ2N7qbqmad/F/M8D7AKDTaQwVzrSIC1dTyy9Z8/YKM2VYgmyB5Iwnz1tyAHrSOuFISsZgAZ0d1RVbY60mr+BnFmp6yYZ89A3e+UvN0duWh2yKeV+X2/Yy9rZVJX46oWbYNR3bu1p1C1951X8SN8J5109zEdPCi6up+dveGlCDxK4dnNGC6da9bZVU3Z7Lt5qr+A3xvc7Urk3v5/SBFMFsXQDMPlScSDuOnAZ3hdJlrMz3xKHPiLKT7qOBq5ATuDjDn6bxs51Lm7Nc5gn/IF01mrbjhEYB8NHV0o8QEcWr0azYr30RZz4rZYdIBAqqe7UXz4D0cODfK8kR1+r+L0UVxWKuZehi5mhLZrAM2ONGsTyZmIj80cPvdON5e2ahAwLzU+yFwdplH8HKOgzjmzPdU9lI8/2C+vyJiRVIOrJpjo=