version: '3.7'

services:

  api:
    build:
      context: ./api
      args:
        - PYTHON_ENV=prod
    container_name: woaq-api
    image: openoakland/woaq-api
    restart: always
    stdin_open: true
    tty: true
    ports:
      - ${API_PORT}
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - DEFAULT_FILE_STORAGE=${DEFAULT_FILE_STORAGE}
      - VIRTUAL_HOST=${API_DOMAIN}
      - VIRTUAL_PORT=${API_PORT}         
    volumes:
      - ./api:/usr/src/app
      - logs:/usr/src/app/logs
    entrypoint:
      - bash
      - -c    

  db:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    image: mdillon/postgis:11
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432
    restart: always

  proxy:
    build:
      context: ./nginx-proxy
      args:
        - CORS_DOMAIN=${API_DOMAIN}
    container_name: woaq-proxy
    image: openoakland/woaq-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro      

volumes:
  logs:
  postgres:      
