version: '3.7'

services:
  db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=woaq
    image: mdillon/postgis:11
  app:
    # NOTE: A command should be passed to the container via docker-compose run. This ensures we don't start
    # gunicorn unnecessarily, and run out of memory.
    entrypoint:
      - bash
      - -c
    links:
      - db
