version: "3"
services:
  api:
    build:
      context: ./api
      args:
        - PYTHON_ENV
    container_name: woaq-api
    image: openoakland/woaq-api
    restart: always
    stdin_open: true
    tty: true
    env_file: .env
    volumes:
      - ./api:/api
      - logs:/logs
  web-dev:
    build:
      context: ./web
    container_name: woaq-web-dev
    image: openoakland/woaq-web-dev
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./web/src:/app/src
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.ci
    container_name: woaq-web
    image: openoakland/woaq-web
    ports:
      - 3000:3000
  proxy:
    container_name: woaq-proxy
    image: nginx:1.15-alpine
    links:
      - api
      - web
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - logs:/var/log/nginx
      - media:/public/media:ro
      - static:/public/static:ro
volumes:
  logs:
  media:
  static:
