version: "3"
services:
  api:
    build:
      context: ./api
      args:
        - PYTHON_ENV
    container_name: woaq.api
    image: openoakland/woaq
    restart: always
    stdin_open: true
    tty: true
    env_file: .env
    volumes:
      - logs:/logs
  web:
    container_name: woaq.web
    image: nginx:1.15-alpine
    links:
      - api
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - logs:/var/log/nginx
      - media:/public/media:ro
      - static:/public/static:ro
volumes:
  logs:
  media:
  static:
